version: '3.8'

services:
  crawler_jobs_mysql:
    image: mysql:8.0
    # 設定 mysql 使用原生認證的密碼 hash
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ACCOUNT: ${MYSQL_ACCOUNT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network



  crawler_jobs_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
          - crawler_jobs_mysql:db
    restart: always
    environment:
      - UPLOAD_LIMIT=128M
      - MEMORY_LIMIT=256M
      - MAX_EXECUTION_TIME=600
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  mysql_data: